### ISSUE TITLE
Hard to manage tags

### ISSUE THREAD

**Issue by NoeTerrier** [clicepfl/NewsMaker#1]
It's hard to add or remove tags: we need to edit the [config file](https://github.com/clicepfl/NewsMaker/blob/main/src/main/resources/config/config.json), change the enum `Tags` in [Format.java](https://github.com/clicepfl/NewsMaker/blob/main/src/main/java/ch/clic/newsmaker/Format.java) and the code in [`createField()`](https://github.com/clicepfl/NewsMaker/blob/main/src/main/java/ch/clic/newsmaker/MainController.java) in order to perform the change. 

The idea is to make it dynamic: only changes in the config file update all the tags in the app. 
- We need to avoid the use of the enum Tags
- The bindings in `createField()` need to be dynamic 
- Setting default values for different languages has to be possible

**Comment by Robb-Fr** [comment]
My reuf, just so I make sure I understand everything, what is a tag ?

**Comment by Robb-Fr** [comment]
<img width="1612" alt="Capture d’écran 2023-01-17 à 08 50 05" src="https://user-images.githubusercontent.com/43422546/212839650-269d2673-0e0f-42d9-b254-91234a335cb9.png">
From there, what is a tag ?

**Comment by NoeTerrier** [comment]
![image](https://user-images.githubusercontent.com/56764430/212842335-add4cfcb-b224-4df3-9a22-b309277cd0d8.png)

If you open [config.json](https://github.com/clicepfl/NewsMaker/blob/1-manage-tags/src/main/resources/config/config.json) and one of the .html template files like [default_news_template.html](https://github.com/clicepfl/NewsMaker/blob/1-manage-tags/src/main/resources/assets/default_news_template.html), you can identify "tags" in the html (\@NEWS_DESCRITPION, \@NEWS_TITLE, ...) which are linked to text-fields values in the config.json (in fact the same as the textfields in your screenshot). This tags in the html will be replaced by their textual value that you can define in the UI (\@NEWS_DESCRITPION will be replaced by the description of the news, \@NEWS_TITLE by its title, etc)

The issue is that if you want to add a @ TAG in an html template like \@AUTHORS_NAME, you currently need to edit the config.json file, the UI, the javaFX bean representing a news field and maybe many other part of the code in order to perform the update.

The idea is now: you only need to update the config.json file if you want to use a new tag in the html and the UI and the model will be updated dynamically.

**Comment by Robb-Fr** [comment]
<img width="1043" alt="Capture d’écran 2023-01-19 à 22 17 59" src="https://user-images.githubusercontent.com/43422546/213562492-a2a70e12-d5f2-42b5-9c83-552367330fe1.png">
<img width="1612" alt="Capture d’écran 2023-01-19 à 22 18 06" src="https://user-images.githubusercontent.com/43422546/213562548-660b820c-9fe0-498a-b991-6c3a1f6f08f5.png">
Would this be the inteded use case ?
